### ISSUE TITLE
Proper Migration Strategy?

### ISSUE THREAD

**Issue by duerra** [twitter/twemproxy#112]
Hey - 
We're looking to migrate from a client-side sharding implementation to Twemproxy.  We use basic crc32 modula with curly bracket ( {} ) hash tag sharding.  We need to be able to migrate to Twemproxy without losing any existing data, and would like the transition to be seamless.

However, as we are testing our Twemproxy configuration, we seem to have encountered a strange situation in that while we have identified keys that map to each of our existing redis instances (128 in total), these don't subsequently map to 128 unique instances in Twemproxy.  We encounter a number of keys that the log file of Twemproxy shows as mapping to the same instance. 

Example: 

``` bash
[Sat May 18 01:30:01 2013] nc_server.c:642 key '197' on dist 1 maps to server '192.168.19.41:6383:127'
[Sat May 18 01:30:04 2013] nc_server.c:642 key '208' on dist 1 maps to server '192.168.19.40:6382:39'
[Sat May 18 01:30:08 2013] nc_server.c:642 key '246' on dist 1 maps to server '192.168.19.41:6383:127'
```

In the example above, we used the "weight" parameter as an identifier in the logs, since it isn't used when the configuration was provided with a server name (as is our case), and the log doesn't output the server name being mapped to.  

Using a basic crc32(key) % 128 on those keys, the first and third entries mod to 0 and 2, respectively (and the 2nd line to "1").  However, as you can see, Twemproxy is assessing those keys as going to the same instance.

Does anybody have any ideas on how to perform this migration in a safe and sane way, without losing any data, or otherwise have any ideas why Twemproxy does not seem to be following the hashing strategy criteria that would seem to be implied based on our configuration?

Configuration is supplied below:

``` yml
rediscluster:
  listen: 192.168.19.123:6000
  redis: true
  hash: crc32
  distribution: modula
  hash_tag: "{}"
  auto_eject_hosts: false
  timeout: 1000
  server_retry_timeout: 2000
  server_failure_limit: 10
  preconnect: true
  server_connections: 1
  servers:
   - 192.168.19.40:6380:1 bucket_1
   - 192.168.19.40:6380:2 bucket_2
   - 192.168.19.40:6380:3 bucket_3
   - 192.168.19.40:6380:4 bucket_4
   - 192.168.19.40:6380:5 bucket_5
   - 192.168.19.40:6380:6 bucket_6
   - 192.168.19.40:6380:7 bucket_7
   - 192.168.19.40:6380:8 bucket_8
   - 192.168.19.40:6380:9 bucket_9
   - 192.168.19.40:6380:10 bucket_10
   - 192.168.19.40:6380:11 bucket_11
   - 192.168.19.40:6380:12 bucket_12
   - 192.168.19.40:6380:13 bucket_13
   - 192.168.19.40:6380:14 bucket_14
   - 192.168.19.40:6380:15 bucket_15
   - 192.168.19.40:6380:16 bucket_16
   - 192.168.19.40:6381:17 bucket_17
   - 192.168.19.40:6381:18 bucket_18
   - 192.168.19.40:6381:19 bucket_19
   - 192.168.19.40:6381:20 bucket_20
   - 192.168.19.40:6381:21 bucket_21
   - 192.168.19.40:6381:22 bucket_22
   - 192.168.19.40:6381:23 bucket_23
   - 192.168.19.40:6381:24 bucket_24
   - 192.168.19.40:6381:25 bucket_25
   - 192.168.19.40:6381:26 bucket_26
   - 192.168.19.40:6381:27 bucket_27
   - 192.168.19.40:6381:28 bucket_28
   - 192.168.19.40:6381:29 bucket_29
   - 192.168.19.40:6381:30 bucket_30
   - 192.168.19.40:6381:31 bucket_31
   - 192.168.19.40:6381:32 bucket_32
   - 192.168.19.40:6382:33 bucket_33
   - 192.168.19.40:6382:34 bucket_34
   - 192.168.19.40:6382:35 bucket_35
   - 192.168.19.40:6382:36 bucket_36
   - 192.168.19.40:6382:37 bucket_37
   - 192.168.19.40:6382:38 bucket_38
   - 192.168.19.40:6382:39 bucket_39
   - 192.168.19.40:6382:40 bucket_40
   - 192.168.19.40:6382:41 bucket_41
   - 192.168.19.40:6382:42 bucket_42
   - 192.168.19.40:6382:43 bucket_43
   - 192.168.19.40:6382:44 bucket_44
   - 192.168.19.40:6382:45 bucket_45
   - 192.168.19.40:6382:46 bucket_46
   - 192.168.19.40:6382:47 bucket_47
   - 192.168.19.40:6382:48 bucket_48
   - 192.168.19.40:6383:49 bucket_49
   - 192.168.19.40:6383:50 bucket_50
   - 192.168.19.40:6383:51 bucket_51
   - 192.168.19.40:6383:52 bucket_52
   - 192.168.19.40:6383:53 bucket_53
   - 192.168.19.40:6383:54 bucket_54
   - 192.168.19.40:6383:55 bucket_55
   - 192.168.19.40:6383:56 bucket_56
   - 192.168.19.40:6383:57 bucket_57
   - 192.168.19.40:6383:58 bucket_58
   - 192.168.19.40:6383:59 bucket_59
   - 192.168.19.40:6383:60 bucket_60
   - 192.168.19.40:6383:61 bucket_61
   - 192.168.19.40:6383:62 bucket_62
   - 192.168.19.40:6383:63 bucket_63
   - 192.168.19.40:6383:64 bucket_64
   - 192.168.19.41:6380:65 bucket_65
   - 192.168.19.41:6380:66 bucket_66
   - 192.168.19.41:6380:67 bucket_67
   - 192.168.19.41:6380:68 bucket_68
   - 192.168.19.41:6380:69 bucket_69
   - 192.168.19.41:6380:70 bucket_70
   - 192.168.19.41:6380:71 bucket_71
   - 192.168.19.41:6380:72 bucket_72
   - 192.168.19.41:6380:73 bucket_73
   - 192.168.19.41:6380:74 bucket_74
   - 192.168.19.41:6380:75 bucket_75
   - 192.168.19.41:6380:76 bucket_76
   - 192.168.19.41:6380:77 bucket_77
   - 192.168.19.41:6380:78 bucket_78
   - 192.168.19.41:6380:79 bucket_79
   - 192.168.19.41:6380:80 bucket_80
   - 192.168.19.41:6381:81 bucket_81
   - 192.168.19.41:6381:82 bucket_82
   - 192.168.19.41:6381:83 bucket_83
   - 192.168.19.41:6381:84 bucket_84
   - 192.168.19.41:6381:85 bucket_85
   - 192.168.19.41:6381:86 bucket_86
   - 192.168.19.41:6381:87 bucket_87
   - 192.168.19.41:6381:88 bucket_88
   - 192.168.19.41:6381:89 bucket_89
   - 192.168.19.41:6381:90 bucket_90
   - 192.168.19.41:6381:91 bucket_91
   - 192.168.19.41:6381:92 bucket_92
   - 192.168.19.41:6381:93 bucket_93
   - 192.168.19.41:6381:94 bucket_94
   - 192.168.19.41:6381:95 bucket_95
   - 192.168.19.41:6381:96 bucket_96
   - 192.168.19.41:6382:97 bucket_97
   - 192.168.19.41:6382:98 bucket_98
   - 192.168.19.41:6382:99 bucket_99
   - 192.168.19.41:6382:100 bucket_100
   - 192.168.19.41:6382:101 bucket_101
   - 192.168.19.41:6382:102 bucket_102
   - 192.168.19.41:6382:103 bucket_103
   - 192.168.19.41:6382:104 bucket_104
   - 192.168.19.41:6382:105 bucket_105
   - 192.168.19.41:6382:106 bucket_106
   - 192.168.19.41:6382:107 bucket_107
   - 192.168.19.41:6382:108 bucket_108
   - 192.168.19.41:6382:109 bucket_109
   - 192.168.19.41:6382:110 bucket_110
   - 192.168.19.41:6382:111 bucket_111
   - 192.168.19.41:6382:112 bucket_112
   - 192.168.19.41:6383:113 bucket_113
   - 192.168.19.41:6383:114 bucket_114
   - 192.168.19.41:6383:115 bucket_115
   - 192.168.19.41:6383:116 bucket_116
   - 192.168.19.41:6383:117 bucket_117
   - 192.168.19.41:6383:118 bucket_118
   - 192.168.19.41:6383:119 bucket_119
   - 192.168.19.41:6383:120 bucket_120
   - 192.168.19.41:6383:121 bucket_121
   - 192.168.19.41:6383:122 bucket_122
   - 192.168.19.41:6383:123 bucket_123
   - 192.168.19.41:6383:124 bucket_124
   - 192.168.19.41:6383:125 bucket_125
   - 192.168.19.41:6383:126 bucket_126
   - 192.168.19.41:6383:127 bucket_127
   - 192.168.19.41:6383:128 bucket_128
```
