### ISSUE TITLE
Request: Allow multiple servers to use same node hash name

### ISSUE THREAD

**Issue by dkong** [twitter/twemproxy#148]
I'd like to have multiple distributed redis slaves associated with the same node name for a couple of reasons:
1. Distribute read-only load across multiple instances
2. Redundancy in case master goes down (one or more slave should be ready to be promoted)

An example topology with three different servers with 1 redis master and 3 redis slaves.

```
Server1

---
master1
slave1a

Server2

---
slave1b

Server3

---
slave1c
```

Proposed config file:

```
masters:
  listen: 127.0.0.1:22122
  hash: fnv1a_64
  hash_tag: "{}"
  distribution: ketama
  auto_eject_hosts: false
  timeout: 400
  redis: true
  servers:
   - 192.168.0.1:6379:1 server1

slaves:
  listen: 127.0.0.1:22123
  hash: fnv1a_64
  hash_tag: "{}"
  distribution: ketama
  auto_eject_hosts: false
  timeout: 400
  redis: true
  servers:
   - 192.168.0.1:6380:1 server1
   - 192.168.0.2:6379:1 server1
   - 192.168.0.3:6379:1 server1
```

Once a redis key is hashed, twemproxy would have 3 servers to choose from (servers 1, 2, or 3).  At that point it could randomly choose, use round-robin, or some other load balancing scheme.

Currently twemproxy [rejects](https://github.com/twitter/twemproxy/blob/master/src/nc_conf.c#L1150) the config file when multiple servers have the same node name.

Are there any gotchas or problems with this idea?

Does anyone have suggestions on the best approach to implement this?

Thanks.
Dara.
