### ISSUE TITLE
FreeBSD. nc_connection.c:401 sendv on sd 1733 failed: Broken pipe

### ISSUE THREAD

**Issue by Sarga** [twitter/twemproxy#179]
Hi, @manjuraj!

I got some servers with FreeBSD ( different versions 9.0-RELEASE-p4 - 9.1-RELEASE-p1) with a twemproxy installed. Also I got 7 servers with memcached with 16GB ram reserved for it, but little bit not enough, so the memcached is being deleting expired and less used keys, we can see the confirmation of this in the statistics STAT evictions 204330668.

Twemproxy is runned with  --mbuf-size=4096, the config file is 

```
memc1:
  listen: /tmp/memcached.1.sock
  preconnect: true
  timeout: 1000
  redis: false
  auto_eject_hosts: false
  server_connections: 20
  server_retry_timeout: 2000
  server_failure_limit: 1
  servers:
   - xx.xxx.xx.xx:11211:1

memc2:
  listen: /tmp/memcached.2.sock
  preconnect: true
  timeout: 1000
  redis: false
  auto_eject_hosts: false
  server_connections: 20
  server_retry_timeout: 2000
  server_failure_limit: 1
  servers:
   - xx.xxx.xx.xx:11211:1

memc3:
  listen: /tmp/memcached.3.sock
  preconnect: true
  timeout: 1000
  redis: false
  auto_eject_hosts: false
  server_connections: 20
  server_retry_timeout: 2000
  server_failure_limit: 1
  servers:
   - xx.xxx.xx.xx:11211:1

memc4:
  listen: /tmp/memcached.4.sock
  preconnect: true
  timeout: 1000
  redis: false
  auto_eject_hosts: false
  server_connections: 20
  server_retry_timeout: 2000
  server_failure_limit: 1
  servers:
   - xx.xxx.xx.xx:11211:1

memc5:
  listen: /tmp/memcached.5.sock
  preconnect: true
  timeout: 1000
  redis: false
  auto_eject_hosts: false
  server_connections: 20
  server_retry_timeout: 2000
  server_failure_limit: 1
  servers:
   - xx.xxx.xx.xx:11211:1

memc6:
  listen: /tmp/memcached.6.sock
  preconnect: true
  timeout: 1000
  redis: false
  auto_eject_hosts: false
  server_connections: 20
  server_retry_timeout: 2000
  server_failure_limit: 1
  servers:
   - xx.xxx.xx.xx:11211:1

memc7:
  listen: /tmp/memcached.7.sock
  preconnect: true
  timeout: 1000
  redis: false
  auto_eject_hosts: false
  server_connections: 20
  server_retry_timeout: 2000
  server_failure_limit: 1
  servers:
   - xx.xxx.xx.xx:11211:1
```

In the twemproxy logs we can see a number of such messages:
[Mon Dec  9 20:44:27 2013] nc_connection.c:401 sendv on sd 146 failed: Broken pipe
[Mon Dec  9 20:44:27 2013] nc_connection.c:401 sendv on sd 1468 failed: Broken pipe
[Mon Dec  9 20:44:36 2013] nc_connection.c:401 sendv on sd 39 failed: Broken pipe
[Mon Dec  9 21:25:49 2013] nc_connection.c:401 sendv on sd 418 failed: Broken pipe
[Mon Dec  9 21:25:49 2013] nc_connection.c:401 sendv on sd 165 failed: Broken pipe
[Mon Dec  9 21:25:49 2013] nc_connection.c:401 sendv on sd 476 failed: Broken pipe

I've also have tried to assembe twemproxy with --enable-debug=log and run it with --verbosity=6.

There are some records in the log like 
[Wed Dec 11 19:05:23 2013] nc_connection.c:401 sendv on sd 943 failed: Broken pipe
[Wed Dec 11 19:05:23 2013] nc_core.c:177 send on c 943 failed: Broken pipe
[Wed Dec 11 19:05:23 2013] nc_core.c:201 close c 943 'unknown' on event FF00 eof 1 done 0 rb 166096 sb 3164797: Broken pipe
[Wed Dec 11 19:05:23 2013] nc_client.c:165 close c 943 discarding completed req 6838388 len 23 type 1
[Wed Dec 11 19:05:23 2013] nc_proxy.c:336 accepted c 62 on p 21 from ':'
[Wed Dec 11 19:05:23 2013] nc_connection.c:401 sendv on sd 842 failed: Broken pipe
[Wed Dec 11 19:05:23 2013] nc_core.c:177 send on c 842 failed: Broken pipe
[Wed Dec 11 19:05:23 2013] nc_core.c:201 close c 842 'unknown' on event FF00 eof 1 done 0 rb 124259 sb 2450608: Broken pipe

Maybe it will be usefull

I've tried to change server_connections: 20 to server_connections: 1, the broken pipe messages were recorded in the log aswell. Maybe its related to the automatic deletion of the keys in memcached servers, and the RAM upgrade could fix it? 
Can you please tell me what are they connected with?

btw, thanks for the software, it's quite usefull.
