### ISSUE TITLE
Lots of connection timeouts on EC2

### ISSUE THREAD

**Issue by rakanalh** [twitter/twemproxy#205]
Hello,

I currently have 3 ec2 instances running 9 instances of Redis (3 each). On this current deployment i have a twemproxy instance on each ec2 instance in front of all 9 redis instances so that all twem proxies have access to all available redis instances. 
The config looks like this:

``` yaml
alpha:
  listen: 0.0.0.0:22121
  redis: true
  hash: fnv1a_64
  distribution: ketama
  auto_eject_hosts: true
  server_retry_timeout: 30000
  server_failure_limit: 2
  timeout: 100
  backlog: 4096
  preconnect: true
  servers:
   - 127.0.0.1:6379:1
   - 127.0.0.1:6380:1
   - 127.0.0.1:6381:1
   - 10.XX.XX.11:6379:1
   - 10.XX.XX.11:6380:1
   - 10.XX.XX.11:6381:1
   - 10.XX.XX.22:6379:1
   - 10.XX.XX.22:6380:1
   - 10.XX.XX.22:6381:1
```

This piece of configuration is also added to the other 2 instances to run twemproxy exactly like the first one.

Using the following redis-benchmark:

```
redis-benchmark -r 10000000 -n 1000000000 -t set -p 22121 -c 1500 -d 4096 -q -l -h PUBLIC_IP_ADDRESS
```

The reason am pushing 1.5K concurrent connections is because am currently seeing numbers close to this on my legacy memcached deployment.

Running the benchmark on one of my servers (other than those 3 used for caching from the same local network) results in lots of server ejections. I shut down the server ejection policy so that i can check what goes on while trying to use one of the redis instances. Here's what i am currently seeing:

``` json
{
   "service":"nutcracker",
   "source":"ip-XX-XX-XX-XXX",
   "version":"0.3.0",
   "uptime":17,
   "timestamp":1394621584,
   "alpha":{
      "client_eof":0,
      "client_err":0,
      "client_connections":1500,
      "server_ejects":0,
      "forward_error":7456,
      "fragments":0,
      "127.0.0.1:6379":{
         "server_eof":1,
         "server_err":0,
         "server_timedout":16,
         "server_connections":0,
         "server_ejected_at":0,
         "requests":840,
         "request_bytes":3482640,
         "responses":0,
         "response_bytes":0,
         "in_queue":0,
         "in_queue_bytes":0,
         "out_queue":0,
         "out_queue_bytes":0
      },
      "127.0.0.1:6380":{
         "server_eof":1,
         "server_err":0,
         "server_timedout":16,
         "server_connections":0,
         "server_ejected_at":0,
         "requests":835,
         "request_bytes":3461910,
         "responses":0,
         "response_bytes":0,
         "in_queue":0,
         "in_queue_bytes":0,
         "out_queue":0,
         "out_queue_bytes":0
      },
      "127.0.0.1:6381":{
         "server_eof":1,
         "server_err":0,
         "server_timedout":16,
         "server_connections":0,
         "server_ejected_at":0,
         "requests":910,
         "request_bytes":3772860,
         "responses":0,
         "response_bytes":0,
         "in_queue":0,
         "in_queue_bytes":0,
         "out_queue":0,
         "out_queue_bytes":0
      }
   }
}
```

I couldn't at first figure out why so i tried playing around with the timeout values, changing them from:
100 to 500 msec -> "forward_error":86619, "server_timedout":86 on all servers
500 - 5000 msec -> "forward_error":0, "server_timedout":0

I played around with preconnect, the number of concurrent clients in the benchmark & the packet sizes of the benchmark as well with no luck. Eventually i turned off the timeouts which made everything good apart from the throughput given by the benchmark which took the set commands / sec from ~ 100 to ~ 250. I think it makes sense because the timeout would limit the wait and cut it off in case something is wrong which is exactly the case.

Can you kindly point out if i need to tune anything other than twemproxy itself to obtain good results? or is the timeout causing the issue and therefore, removing it would be the workaround?

Thanks
