### ISSUE TITLE
Cannot Get This Working

### ISSUE THREAD

**Issue by jamescarr** [twitter/twemproxy#251]
I have a real need for this and it exactly solves a problem I have, but I cannot get it to work aside from viewing stats. I'm frustrated! What am I doing wrong here, there are no error logs even when verbosity is set to 11. 

My supervisor config (this is in docker):

```
[supervisord]
nodaemon=true

[program:nutcracker]
command=/usr/local/bin/nutcracker -c /etc/nutcracker/memcache.yaml -s 22222 -v 11 -o /var/log/nutcracker

[program:memcache1]
command=/usr/bin/memcached -p 11211
user=memcache

[program:memcache2]
command=/usr/bin/memcached -p 11212
user=memcache

```

My /etc/nutcracker/memcache.yaml

```
gamma:
  listen: 127.0.0.1:22123
  hash: fnv1a_64
  distribution: ketama
  timeout: 400
  backlog: 1024
  preconnect: true
  auto_eject_hosts: false
  server_retry_timeout: 2000
  server_failure_limit: 3
  servers:
   - 127.0.0.1:11211:1
   - 127.0.0.1:11212:1
```

Testing the config says it is okay. All required ports are open, connecting to individual memcache instances work, connecting to 127.0.0.1:22123 connects but fails issuing any commands. 

Call to status port via telnet yields:

``` json

{
  "service": "nutcracker",
  "source": "ultimate",
  "version": "0.3.0",
  "uptime": 830,
  "timestamp": 1408478717,
  "gamma": {
    "client_eof": 0,
    "client_err": 0,
    "client_connections": 0,
    "server_ejects": 0,
    "forward_error": 0,
    "fragments": 0,
    "127.0.0.1:11212": {
      "server_eof": 0,
      "server_err": 0,
      "server_timedout": 0,
      "server_connections": 1,
      "server_ejected_at": 0,
      "requests": 0,
      "request_bytes": 0,
      "responses": 0,
      "response_bytes": 0,
      "in_queue": 0,
      "in_queue_bytes": 0,
      "out_queue": 0,
      "out_queue_bytes": 0
    },
    "127.0.0.1": {
      "server_eof": 0,
      "server_err": 0,
      "server_timedout": 0,
      "server_connections": 1,
      "server_ejected_at": 0,
      "requests": 0,
      "request_bytes": 0,
      "responses": 0,
      "response_bytes": 0,
      "in_queue": 0,
      "in_queue_bytes": 0,
      "out_queue": 0,
      "out_queue_bytes": 0
    }
  }
}

```

cat of /var/log/nutcracker.log

```
[Tue Aug 19 19:51:27 2014] nc.c:187 nutcracker-0.3.0 built for Linux 3.13.0-24-generic x86_64 started on pid 182
[Tue Aug 19 19:51:27 2014] nc.c:192 run, rabbit run / dig that hole, forget the sun / and when at last the work is done / don't sit down / it's time to dig another one

```

Any ideas what I am doing wrong here???

What gives?? I have been connecting via the raw telnet protocol and pylibmemcache, no dice.
