### ISSUE TITLE
Lots of Connection Resets

### ISSUE THREAD

**Issue by jamescarr** [twitter/twemproxy#258]
We recently launched twemproxy with memcached into our environment and I've been seeing connection resets... a lot of them.

![screen shot 2014-09-08 at 1 16 56 am](https://cloud.githubusercontent.com/assets/45389/4181774/28fff624-3722-11e4-93ed-d121299f1d14.png)

Some details:
- We run five servers with memcached running with 17g of ram available
- we run two twemproxy servers 
- we have over 5k clients making calls to the two twemproxy servers 

Out nutcracker configuration: 

```
gamma:
  auto_eject_hosts: false
  distribution: ketama
  hash: fnv1a_64
  hash_tag: 'P:'
  listen: 0.0.0.0:22121
  servers:
  - 10.0.12.192:11211:1 rawhide
  - 10.0.11.58:11211:1 optimus
  - 10.0.10.124:11211:1 ratchet
  - 10.0.11.145:11211:1 bumblebee
  - 10.0.11.152:11211:1 megatron
  timeout: 500
```

How can I find out more details about what is up?
