### ISSUE TITLE
"MGET {a}1 {b}1" crashes Twem to seg fault

### ISSUE THREAD

**Issue by hdv** [twitter/twemproxy#285]
Please ignore config in this message, there's a second message from me and it has better explanation of what needs to be configured to reproduce the issue.

```
"redis-cli -h <HOST> MGET {a}1 {a}1" - works fine
"redis-cli -h <HOST> MGET {a}1 {b}1" - produces the following:
```

```
Error: Server closed the connection
```

Config file:

```
## core Twemproxy config
redis1:
  listen: 0.0.0.0:6379
  database: 4
  redis: true
  hash: fnv1a_64
  distribution: ketama
  auto_eject_hosts: true
  timeout: 400
  server_retry_timeout: 20000
  server_failure_limit: 3
  servers:
   - xxx:yyy:1
   - xxx:zzz:1
...
```

Note: hash_tag parameter is not specified!

The issue can't be reproduced on v0.3.0.

Let me know if I need to provide any more info.

Thank you in advance!
