### ISSUE TITLE
Out of memory crash

### ISSUE THREAD

**Issue by alicebob** [twitter/twemproxy#296]
We're trying to set up a 32 node 'cluster', but we're having some trouble with populating the cluster (twemproxy runs out of memory and crashes).

Twemproxy itself runs and works fine in normal usage, it's only when we want to fill it things go haywire. The idea is to use the AOF file of the old redis instance and pipe it into the new twemproxy using:
`cat our_aof_file | redis-cli -h localhost -p 6380 -a ourpassword --pipe --pipe-timeout 10`

That works fine for a few seconds, we get keys in redis, but then the memory blows up and twemproxy crashes. When we feed the commands a little slower (send 10K commands, sleep a second, GOTO 1), it works for a few minutes and memory usage is stable (somewhere in the single GB range), but then suddenly everything blows up again. I'm trying to make a producible test case which doesn't involve an aof file with 10M commands, but maybe someone has a clue in the meantime.

The twemproxy is from master, we tried this also without authentication.

Twemproxy.yml:

``` yaml
pool:
  listen: localhost:6380
  hash: fnv1a_64
  distribution: ketama
  auto_eject_hosts: false
  timeout: 400
  redis: true
  redis_auth: ourpassword
  servers:
  - 10.0.2.20:6379:1 shard0
  <32 of those>
```
