### ISSUE TITLE
configuration file 'conf/nutcracker.yml' syntax is invalid

### ISSUE THREAD

**Issue by NoDurex** [twitter/twemproxy#38]
Hello  , I   got  the  lastest  brach .
And   edit  the  nutcracker.yml  as

```
leaf:
  listen: 127.0.0.1:22121
  hash: fnv1a_64
  distribution: ketama
  auto_eject_hosts: true
  server_retry_timeout: 2000
  server_failure_limit: 1
  servers:
   - 127.0.0.1:11212:1
   - 127.0.0.1:11213:1

```

then  test  bash  $ nutcracker   -t

but  it   told  me : 

configuration file 'conf/nutcracker.yml' syntax is invalid

however  I   edit  it    as  root.yml ,but it  also   dont  work.
