### ISSUE TITLE
Uneven cache hits

### ISSUE THREAD

**Issue by rohitpaygude** [twitter/twemproxy#408]
Hi all,

I have integrated twemproxy into web layer and I have 6 Elasticache(1 master , 5 read replicas) I am getting issue that the all replicas have same keys everything is same but cache hits on one replica is way more than others and I performed several load testing still on every test I am getting same result. I have separate data engine that writes on the master of this cluster and remaining 5 replicas get sync with it. So I am using twemproxy only for reading data from Elasticache not for sharding purpose. So my simple question is why i am getting 90% of hits on single read replicas of Elasticache it should distribute the hits evenly among all read replicas? right?

**Comment by manjuraj** [comment]
your keyspace is not uniformly distributed

**Comment by zmijevik** [comment]
@manjuraj I have a similar issue with "uneven" cache hits which is most likely something wrong with my nutcracker configuration. Can you please recommend something? I have scoured the internet which brings me right back to this repository. Here is my nutcracker config:

```
alpha:
  listen: 0.0.0.0:22122
  hash: fnv1a_64
  hash_tag: "{}"
  distribution: ketama
  auto_eject_hosts: true
  server_retry_timeout: 30000
  server_failure_limit: 3
  timeout: 400
  redis: true
  preconnect: true
  redis_auth: erfygeruyfgeryufgeuyrf
  servers:
   - 10.132.166.170:6379:1 redis-001
   - 10.132.166.170:6380:1 redis-002
   - 10.132.166.170:6381:1 redis-003
   - 10.132.166.170:6382:1 redis-004
   - 10.132.166.170:6383:1 redis-005
```

Here is an example of the keys all being stored in redis-001 instance:

> keys *
```
 1) "images:{Mochi Frozen Yogurt}:https://static.accessdevelopment.com/brand/3095fa9e87608807fb3cd4141ae5816d459f7ef6/original.png"
 2) "images:{Avis Car Rental}:https://static.accessdevelopment.com/brand/7444e414a1828fdfc3c2f826c7babdff99daa854/original.png"
 3) "images:{Papa John's\xc2\xae}:https://static.accessdevelopment.com/brand/31c0f56aef560bf684961319619e156aac4dcdec/original.png"
 4) "images:{Spa & Wellness Gift Cards}:https://static.accessdevelopment.com/brand/a668b14fae318bc23c1fa2b3118c57e6a94ffeb8/original.png"
```

Is there a reason why all the keys are being written to redis1 only? How to evenly distribute the keys based on the hash tag to all 5 replicas?
