### ISSUE TITLE
Invalid argument

### ISSUE THREAD

**Issue by NoDurex** [twitter/twemproxy#43]
hello,i set two proxy like :

```
nodurex0:
  listen: 192.168.0.22:23333
  hash: fnv1a_64
  distribution: ketama
  auto_eject_hosts: true
  server_retry_timeout: 2000
  server_failure_limit: 1
  servers:
   - 192.168.0.22:15555:1       
   - 192.168.0.22:16666:1


nodurex1:
  listen: 192.168.0.22:24444 
  hash: fnv1a_64 
  distribution: ketama
  auto_eject_hosts: true
  server_retry_timeout: 2000 
  server_failure_limit: 1
  servers:
   - 192.168.0.22:17777:1       
   - 192.168.0.22:18888:1
```

And   when my   java  memcache client  set a  vaklue  to  the memcache, it takes  me 

```
[Fri Jan  4 11:28:36 2013] nc_core.c:207 close c 46 '192.168.0.155:62851' on event 0001 eof 0 done 0 rb 9 sb 0: Invalid argument
[Fri Jan  4 11:28:36 2013] nc_core.c:207 close c 16 '192.168.0.155:62821' on event 0001 eof 0 done 0 rb 9 sb 0: Invalid argument
[Fri Jan  4 11:28:36 2013] nc_core.c:207 close c 31 '192.168.0.155:62836' on event 0001 eof 0 done 0 rb 9 sb 0: Invalid argument
[Fri Jan  4 11:28:36 2013] nc_core.c:207 close c 32 '192.168.0.155:62837' on event 0001 eof 0 done 0 rb 9 sb 0: Invalid argument
[Fri Jan  4 11:28:36 2013] nc_core.c:207 close c 47 '192.168.0.155:62852' on event 0001 eof 0 done 0 rb 9 sb 0: Invalid argument
[Fri Jan  4 11:28:36 2013] nc_core.c:207 close c 17 '192.168.0.155:62822' on event 0001 eof 0 done 0 rb 9 sb 0: Invalid argument
```

i  konw  it  becomes   one port to  copy  to  another.   But   i   don't  konw   how  to  fix  it.
