### ISSUE TITLE
Blocking connect on host down

### ISSUE THREAD

**Issue by arnecls** [twitter/twemproxy#442]
**Overview**
We encountered a strange behavior when a memcached host out of a ketama pool is taken down (by pulling the network cable).  
Twemproxy is returning timeouts directly after the server becomes unreachable. However, after the ARP cache is flushed (every 20min on FreeBSD) twemproxy suddenly starts to return server errors and the response time increases for every reconnection attempt.

**Version and OS**
Twemproxy 0.4.1
Freebsd 10.1

**Webserver load metrics**
![response](https://cloud.githubusercontent.com/assets/6131989/11688263/df160c06-9e8b-11e5-9c95-9d849e8f4e98.png)

**Twemproxy error metrics**
![errors](https://cloud.githubusercontent.com/assets/6131989/11688250/c489b0a4-9e8b-11e5-8301-1fdfcd33e1b6.png)

**Twemproxy config**
24 memcached pools like this:
```
memcached_default:
  listen: /var/run/twemproxy/memcached_default.socket 0777
  hash: md5
  distribution: ketama
  auto_eject_hosts: true
  backlog: 2048
  preconnect: true
  server_retry_timeout: 30000
  server_failure_limit: 3
  timeout: 300
  servers:
    - 1.2.3.1:11211:1
    - 1.2.3.2:11211:1
    - 1.2.3.3:11211:1
    - 1.2.3.4:11211:1
    - 1.2.3.5:11211:1
    - 1.2.3.6:11211:1
```

**example error log entry**
```
[2015-12-02 9:30:58.884] nc_server.c:531 connect on s 3462 to server '10.2.3.45:11233:1' failed: Host is down
```

**Investigation**
The error above is produced by nc_server.c:552 (the log entry is misleading), which is strange as the socket is created as non-blocking (nc_server.c:516). In case of a non blocking socket a "Host is down" error should have been returned by select or in this case kevent as in nc_kqueue.c:273 ff..  
We actually see this happen before the ARP cache flush, because when kevent produces an error a timeout and forward error is logged (and you can follow that codepath quite easily).  
This is what we see in the first part of the twemproxy error graph.
The second part however is clearly caused by connect() from nc_server.c as the corresponding error messages appear exactly when the server errors start appearing and the response times go up.

The conclusion we draw from that is that connect() is blocking twemproxy after the ARP cache is flushed. With a blocking code path timeouts are multiplied by the set retry count (i.e. 3x300ms). In case of the async kevent code path 3 or more events can be processed in parallel, i.e. there is only a timeout of ~300ms. This explains why we see an increase of repsonse time after the ARP flush.

The only problem here is that no timeout is ever set for connect. So this call is probably not responsible for a blocking behavior.

I think that the failing connect is indirectly responsible for triggering a timeout on kevent because of an empty queue (or sth. like that). In combination with that it might be that connect() is actually returning an error from a previous attempt.

It would be great if someone with a little more knowledge on kevent and/or async sockets could have a look at this.
