### ISSUE TITLE
redis client connection not closed

### ISSUE THREAD

**Issue by Cphilo** [twitter/twemproxy#449]
When I use twemproxy, I connect twemproxy with python  redis client, the client connection grows to the limit 10000. But I use it as  a connection pool with max connections 100, it should not happened. Instead, I directly insert data into redis server, the client connection keep stable not grows constantly. I guess that the client connection cannot be closed from the redis client. Twemproxy should do that.

```bash
root@node1:~/ssdb_benchmark# nutcracker --version
This is nutcracker-0.4.1
```

 Here is my twemproxy `nutcracker.yml` file
```
ssdb_cluster:
  listen: 192.168.0.202:4001
  hash: fnv1a_64
  distribution: ketama
  auto_eject_hosts: false
  redis: true
  server_connections: 10000
  preconnect: true
  server_retry_timeout: 2000
  server_failure_limit: 1
  servers:
   - 192.168.0.201:8888:1
   - 192.168.0.202:8888:1

redis_cluster:
  listen: 192.168.0.202:4002
  hash: fnv1a_64
  distribution: ketama
  auto_eject_hosts: false
  redis: true
  server_connections: 10000
  preconnect: true
  server_retry_timeout: 2000
  server_failure_limit: 1
  servers:
   - 192.168.0.201:6379:1
   - 192.168.0.202:6379:1
```

And here is my python test script
```python
import os, sys
from sys import stdin, stdout
from random import randint
import redis

f = open("test.html").read()
settings = {
    "SSDBIp": "xx",
    "SSDBPort": xx
}
conn_pool = redis.ConnectionPool(host=settings["SSDBIp"], port=settings["SSDBPort"], max_connections=100)
r = redis.Redis(connection_pool=conn_pool)

def bench_mark(content):
    r.set(str(randint(1, 10000000000)), content)

if __name__ == "__main__":
    cnt = 0
    for i in xrange(100000):
        cnt += 1
        if cnt % 1000 == 0:
            print cnt
        bench_mark(f)
```
