### ISSUE TITLE
Feature request: reads/writes routing with Redis.

### ISSUE THREAD

**Issue by pavel-shpilev** [twitter/twemproxy#455]
Hi.

A couple of projects I am currently working on would greatly benefit if twemproxy supported routing for reads and writes. I imagine this could be a quite useful feature for many others as well.

Let me explain what I mean. I have a Redis cluster with one master and a bunch of slaves. Reads to writes ratio in my scenario is at least 100:1. Immediate availability of writes across all the slaves isn't a concern, and Redis replication serves the purpose just fine. I want to have a single nutcracker setup that would look something like this:

```
alpha:
  auto_eject_hosts: true
  read_distribution: random
  write_distribution: one_at_a_time
  hash: murmur
  listen: 127.0.0.1:6379
  preconnect: true
  redis: true
  redis_db: 1
  server_failure_limit: 3
  server_retry_timeout: 5000
  timeout: 20000
  read_servers:
  - read-001.84omyv.0001.use1.cache.amazonaws.com:6379:1
  - read-002.84omyv.0001.use1.cache.amazonaws.com:6379:1
  - read-003.84omyv.0001.use1.cache.amazonaws.com:6379:1
  write_servers:
  - write-001.84omyv.0001.use1.cache.amazonaws.com:6379:1
```

Currently I do routing on application level by handling two connections: one direct to write node and one to nutcracker balancing the reads. This task, however, appears to me common enough to be implemented as twemproxy feature. It would allow to decouple infrastructure configuration and business logic.

I can start working on the feature myself, but before that I would like to know the maintainers opinion whether it worth looking at. Perhaps there are some obvious obstacles that defeat the purpose, that I am missing.

Thank you.
