### ISSUE TITLE
key remap not working

### ISSUE THREAD

**Issue by bymaximus** [twitter/twemproxy#472]
I'm testing with 2 servers
```
root:
  listen: 192.168.0.3:16378
  hash: fnv1a_64
  distribution: ketama
  preconnect: true
  timeout: 5000
  auto_eject_hosts: true
  server_retry_timeout: 30000
  server_failure_limit: 2
  redis: true
  servers:
   - 127.0.0.1:6379:1 server1
   - xxxx.com:6379:1 server2
```

I add key 'aaa' with some value and then I check with redis-cli which one of both servers have the key 'aaa' and then I stop the target server. At twemproxy I try get the key 'aaa' which return connection dropped and then in the next get key request returns null, is ok. 

Then I set the key 'aaa' again with some other value and then I start the other server, twemproxy shows the key 'aaa' new value until it reconnects to the server I stopped and then start showing the key 'aaa' first value. It should not remap this key 'aaa' to the last server I set the key value?
