### ISSUE TITLE
client_connections doesn't work?

### ISSUE THREAD

**Issue by Shanicky** [twitter/twemproxy#477]
Hi, any

I'm using twemproxy in v0.4.1
```
# nutcracker -V
This is nutcracker-0.4.1
```
And I'm using this config

```yaml
proxy01:
  listen: 0.0.0.0:8001
  auto_eject_hosts: false
  hash: fnv1a_64
  distribution: modula
  redis: true
  preconnect: true
  timeout: 300
  client_connections: 1
  servers:
  - localhost:7001:1 redis7001
  - localhost:7002:1 redis7002
```

I've set `client_connections` to 1, but when I run redis-benchmark with `-c` flag to start multi clients like this 
`redis-benchmark -t get -c 5 -p 8001 -n 10000000`

It didn't get any errors. The result of status port is like this 

```

{
   "source" : "twemproxy01",
   "curr_connections" : 8,
   "version" : "0.4.1",
   "total_connections" : 48,
   "service" : "nutcracker",
   "proxy01" : {
      "redis7001" : {
         "request_bytes" : 0,
         "server_timedout" : 0,
         "requests" : 0,
         "server_ejected_at" : 0,
         "out_queue_bytes" : 0,
         "in_queue_bytes" : 0,
         "out_queue" : 0,
         "in_queue" : 0,
         "response_bytes" : 0,
         "server_err" : 0,
         "responses" : 0,
         "server_eof" : 0,
         "server_connections" : 1
      },
      "client_eof" : 35,
      "forward_error" : 0,
      "fragments" : 0,
      "redis7002" : {
         "request_bytes" : 23035068,
         "server_timedout" : 0,
         "requests" : 639863,
         "server_ejected_at" : 0,
         "out_queue_bytes" : 72,
         "in_queue_bytes" : 0,
         "out_queue" : 2,
         "in_queue" : 0,
         "response_bytes" : 3199305,
         "server_err" : 0,
         "responses" : 639861,
         "server_eof" : 0,
         "server_connections" : 1
      },
      "client_err" : 5,
      "client_connections" : 5,
      "server_ejects" : 0
   },
   "timestamp" : 1467099733,
   "uptime" : 126
}

```

It looks like that `client_connections` does not work.
