### ISSUE TITLE
how twemproxy write to memcach server 

### ISSUE THREAD

**Issue by haihq88** [twitter/twemproxy#507]
I have following setting for PHP session 
```
session_cached:
  listen: 127.0.0.1:22123
  hash: fnv1a_64
  distribution: ketama
  timeout: 400
  backlog: 1024
  preconnect: true
  auto_eject_hosts: true
  server_retry_timeout: 2000
  server_failure_limit: 3
  servers:
    - 10.16.223.249:11211:1 b1
    - 10.16.223.254:11211:1 b2
    - 10.16.223.221:11211:1 b3
    - 10.16.223.204:11211:1 b4
```
When session created, how it write to each memcache servers? 
As i know, twemproxy is consistent hashing. Can we define number of memcache server will be written? for example, memcache has option memcache.session_redundancy=N
