### ISSUE TITLE
Twemproxy (Redis) for large batch/small # of connections

### ISSUE THREAD

**Issue by praveenbalaji-blippar** [twitter/twemproxy#539]
I use Redis in our offline processing (large batch/small # of connections). I want to use twemproxy to partition data. I want to be able to solve 2 issues:

- I notice that the performance drops 2x when I use twemproxy.
- Of greater concern to me is that twemproxy seems to drop the connection intermittently. I tried various `--mbuf-size` ranging from the default (16K) to 16M.

I looked through several Issues on github, but most use cases seem to be large # of connection/online use cases. I want to figure out the configuration to handle large batch/small # of connections instead. Suggestions are much appreciated.

On an 8-core machine, `top` shows that available memory is not a problem. However, twemproxy appears to consume >90% CPU. The Redis instances consume ~10% CPU. When I connect directly to a Redis instance to execute the same commands, Redis consumes >90% CPU.

The configuration is as follows:
```
test:
  listen: 0.0.0.0:6378
  hash: fnv1a_64
  distribution: ketama
  auto_eject_hosts: true
  redis: true
  server_retry_timeout: 2000
  server_failure_limit: 1
  servers:
   - 127.0.0.1:7378:1
   - 127.0.0.1:7379:1
```

Our use case has the following characteristics:

- pipelined request with `del`. Each pipelined request has 200,000 - 2,000,000 commands (set + sadd). Each key is ~10 bytes.
- `mget` batches of size 100,000 - 1,000,000. Each key and value are ~10 bytes.
- pipelined request with `set` and `sadd`. Each pipelined request has 200,000 - 2,000,000 commands (set + sadd). Each key and value is ~10 bytes.
