### ISSUE TITLE
Redis / Error: Connection reset by peer

### ISSUE THREAD

**Issue by elegos** [twitter/twemproxy#549]
Hello!

I'm trying to setup nutcracker to split the traffic between two redis servers on the same machine in a docker environment.

I've setup the two redis servers (redis_1 and redis_2) to listen on port 6379 and nutcracker on port 21121 (host: 6379). So the internal docker network has these endpoints:

- redis_1:6379
- redis_2:6379
- nutcracker:21121 -> 0.0.0.0:6379

This is the nutcracker's configuration:

```
alpha:
  listen: 127.0.0.1:21121
  hash: fnv1a_64
  distribution: ketama
  auto_eject_hosts: true
  redis: true
  redis_db: 0
  server_retry_timeout: 30000
  server_failure_limit: 3
  timeout: 400
  servers:
    - redis_1:6379:1 cache0p0
    - redis_2:6379:1 cache0p1

```

I can enter the nutcracker instance via redis-cli, but when I try to actually write some data, I always get the "Connection reset by peer" error:

```
$ redis-cli
127.0.0.1:6379> SET A 1
Error: Connection reset by peer
```

Entering the nutcracker's docker instance (bash) I can correctly ping redis_1 and redis_2.

Am I doing anything wrong?

This is my docker-compose file:
```
version: "2.3"
services:
  nutcracker:
    image: giacomofurlan/twemproxy
    links:
      - redis_1
      - redis_2
    ports:
      - 6379:21121
    privileged: true
    restart: always
    sysctls:
      net.core.somaxconn: 65535
    volumes:
      - ./nutcracker.yml:/usr/local/etc/nutcracker/nutcracker.yml
  redis_1:
    command: redis-server /usr/local/etc/redis/redis.conf
    image: redis:4
    privileged: true
    restart: always
    sysctls:
      net.core.somaxconn: 65535
    volumes:
      - redis_data_1:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
  redis_2:
    command: redis-server /usr/local/etc/redis/redis.conf
    image: redis:4
    privileged: true
    restart: always
    sysctls:
      net.core.somaxconn: 65535
    volumes:
      - redis_data_2:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
volumes:
    redis_data_1:
    redis_data_2:
```

This is the docker file used to compile and run nutcracker: https://github.com/elegos/docker-twemproxy/blob/master/Dockerfile

Thank you very much :)
