### ISSUE TITLE
Twemproxy going OOM

### ISSUE THREAD

**Issue by auror** [twitter/twemproxy#553]
Hi,

We're running twemproxy behind set of memcached servers. Below's the obfuscated config

```
some_pool:
  listen: 127.0.0.1:11213
  hash: crc16
  distribution: ketama
  backlog: 4000
  timeout: 30
  preconnect: true
  server_connections: 200
  auto_eject_hosts: false
  server_retry_timeout: 2000
  servers:

   - some_host_port:1 k1
   - some_host_port:1 k2
   - some_host_port:1 k3
   - some_host_port:1 k4
   - some_host_port:1 k5
   - some_host_port:1 k6
   - some_host_port:1 k7
   - some_host_port:1 k8
   - some_host_port:1 k9
   - some_host_port:1 k10
   - some_host_port:1 k11
   - some_host_port:1 k12
```

1. Clients connected to Twemproxy issue a single GET command
2. The throughput is constant and is ~ 2.2K QPS
3. No: of clients connected to twemproxy is fairly low number < 100
4. No: of items in In Queue(and in_queue_bytes) is very less

At some point twemproxy started using very large amount of memory. Also saw the connection timeouts around the same time: `close s: Connection timed out` in debug logs

Memory consumption grows high until Kernel kills the nutcracker instance
