### ISSUE TITLE
twemproxy with specific keys

### ISSUE THREAD

**Issue by edenisn** [twitter/twemproxy#555]
I have config file for twemproxy:

 ```
redis1:
  listen: 0.0.0.0:6380
  redis: true
  hash: fnv1a_64
  distribution: ketama
  auto_eject_hosts: true
  timeout: 10000
  server_retry_timeout: 10000
  server_failure_limit: 5
  servers:
   - 0.0.0.0:6379:1 server0
   - 0.0.0.1:6379:1 server1
```
Can we use twemproxy with specific keys for a separate redis server? How to do that?
