### ISSUE TITLE
Not working redis-sentinel-feature

### ISSUE THREAD

**Issue by 5st7** [twitter/twemproxy#666]
I'm trying [redis-sentinel-feature](https://github.com/twitter/twemproxy/blob/master/notes/redis.md#redis-sentinel-feature).

Startup failed：
```
nc_conf.c:1070 conf: '/etc/nutcracker.conf' has more than one sequence directive
malexer-twemproxy  | nutcracker: configuration file '/etc/nutcracker.conf' syntax is invalid
```

I use nutcracker.yml as a sample.
```
  sigma:
    listen: 127.0.0.1:22125
    hash: fnv1a_64
    distribution: ketama
    auto_eject_hosts: false
    redis: true
    server_retry_timeout: 2000
    server_failure_limit: 1
    servers:
      - 127.0.0.1:6379:1 server1
      - 127.0.0.1:6380:1 server2
    sentinels:
      - 127.0.0.1:26379:1
      - 127.0.0.1:26380:1
      - 127.0.0.1:26381:1

```
Is that any error on my nutcracker.yml?
or is it not supported yet?
