### ISSUE TITLE
Map to same server

### ISSUE THREAD

**Issue by mezzatto** [twitter/twemproxy#78]
Is there a way, using modula distribution, to map keys to a server in the way showed bellow?

```
pool:
  listen: 127.0.0.1:22121
  hash: crc32
  distribution: modula
  redis: true
  servers:
   - 127.0.0.1:6379:1 Server0
   - 127.0.0.1:6379:1 Server1
   - 127.0.0.1:6380:1 Server2
   - 127.0.0.1:6380:1 Server3
```

I would expect "if HASH MOD NUM_SERVERS" to be like this:

== 0, the key goes to Server0,
== 1, the key goes to Server1, 
== 2, the key goes to Server2
== 3, the key goes to Server3

But I cannot put servers with same name (ip:port:weight) at the same pool.

The setup that I'm trying to come up with is one that could minimize the TCP connection of my system by running nutcracker at both client and server machines. I want to migrate my current setup in which every client connect to every server to something like this:

Client Machine 1:
Client A (M1CA)
Client B (M1CB)

Client Machine 2:
Client A (M2CA)
Client B (M2CB)

Server Machine 1:
Server A (M1SA)
Server B (M1SB)

Server Machine 2:
Server A (M2SA)
Server B (M2SB)

Without nutcracker, I have 16 TCP connection (4 clients \* 4 servers). With nutcracker in Client or Server machines I have 8 TCP connections (2 client/server \* 4 client/server). But I want to have 4 TCP connection (2 client machines \* 2 server machines) by adding nutcracker to both server and client machines.

Of course the above is a simple example. My system has actually thousands of TCP connection (hundreds clients connecting to hundreds servers).

The ideia is that the nutcracker in the client maps to a nutcracker in the server that finally maps to the right redis instance.

Any thoughts?
