### ISSUE TITLE
Why stat client_err is equal to requests?

### ISSUE THREAD

**Issue by ghost** [twitter/twemproxy#90]
test environment 
- ubuntu 12.04 LTS 64bit
- nginx/1.1.19, PHP 5.4.10/PHP-FPM
- twemproxy/nutcracker-0.2.3

PHP test script redis-uds.php

```
<?php
error_reporting(E_ALL);
$r = new Redis();
$r->connect('/tmp/redis.sock');
echo $r->incr("counter");
```

redis start command

```
redis-server --port 6379 
```

nutcracker configuration file redis.yml 

```
alpha:
  listen: /tmp/redis.sock
  hash: fnv1a_64
  distribution: ketama
  auto_eject_hosts: true
  redis: true
  server_retry_timeout: 2000
  server_failure_limit: 1
  servers:
  - 127.0.0.1:6379:1
```

stats reports 

```
$ curl -s  http://127.0.0.1:22222/ | python -mjson.tool
{
"alpha": {
    "127.0.0.1:6379": {
    "in_queue": 0, 
    "in_queue_bytes": 0, 
    "out_queue": 0, 
    "out_queue_bytes": 0, 
    "request_bytes": 20304, 
    "requests": 752, 
    "response_bytes": 4404, 
    "responses": 752, 
    "server_connections": 1, 
    "server_eof": 0, 
    "server_err": 0, 
    "server_timedout": 0
    }, 
    "client_connections": 0, 
    "client_eof": 0, 
    "client_err": 752, 
    "forward_error": 0, 
    "fragments": 0, 
    "server_ejects": 0
}, 
"service": "nutcracker", 
"source": "ubuntu-company", 
"timestamp": 1363686268, 
"uptime": 8, 
"version": "0.2.3"
}
```

Why stat client_err is equal to requests?
